services:
  petstoreapp:
    build:
      context: ./petstoreapp
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - APPLICATIONINSIGHTS_ENABLED=true
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
      - PETSTOREORDERITEMSRESERVER_URL=http://petstoreorderitemsreserver:80
      # Enables External ID login/logout flow locally. Set additional configs in .env:
      - PETSTORE_SECURITY_ENABLED=true

  petstorepetservice:
    build:
      context: ./petstorepetservice
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
      - PETSTOREPETSERVICE_DB_URL=${PETSTOREPETSERVICE_DB_URL}
      - PETSTOREPETSERVICE_DB_USERNAME=${PETSTOREPETSERVICE_DB_USERNAME}
      - PETSTOREPETSERVICE_DB_PASSWORD=${PETSTOREPETSERVICE_DB_PASSWORD}

  petstoreproductservice:
    build:
      context: ./petstoreproductservice
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
      - PETSTOREPRODUCTSERVICE_DB_URL=${PETSTOREPRODUCTSERVICE_DB_URL}
      - PETSTOREPRODUCTSERVICE_DB_USERNAME=${PETSTOREPRODUCTSERVICE_DB_USERNAME}
      - PETSTOREPRODUCTSERVICE_DB_PASSWORD=${PETSTOREPRODUCTSERVICE_DB_PASSWORD}

  petstoreorderservice:
    build:
      context: ./petstoreorderservice
    ports:
      - "8083:8083"
    env_file:
      - .env
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}

  petstoreorderitemsreserver:
    build:
      context: ./petstoreorderitemsreserver
    ports:
      - "8085:80"
    env_file:
      - .env
    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
      - AzureWebJobsStorage=
      - BLOB_STORAGE_CONNECTION_STRING=${BLOB_STORAGE_CONNECTION_STRING}
      - BLOB_STORAGE_CONTAINER_NAME=orderitemsreserver
