spring:
  application:
    name: petstoreproductservice
  datasource:
    url: ${PETSTOREPRODUCTSERVICE_DB_URL:jdbc:postgresql://localhost:5432/petstore}
    username: ${PETSTOREPRODUCTSERVICE_DB_USERNAME:petstore}
    password: ${PETSTOREPRODUCTSERVICE_DB_PASSWORD:petstore}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: petstore
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false

server:
  port: ${PETSTOREPRODUCTSERVICE_SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    ssl:
      enabled: false
    diskspace:
      enabled: false
